'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
const PROGRAMS=new Set(['BEED','BSED','BSA','BSAIS','BSBA']),BSED=new Set(['English','Filipino','Mathematics','Science']),BSBA=new Set(['MM','FM','HRM']),DEFENSES=new Set(['title','proposal','final'])
const clean=(v:FormDataEntryValue|null)=>String(v??'').trim()
function fail(id:string,message:string):never{redirect(`/admin/groups/${id}/edit?error=${encodeURIComponent(message)}`)}
export async function saveResearchGroupEdits(formData:FormData){
 const id=clean(formData.get('groupId')),title=clean(formData.get('title')),program=clean(formData.get('program')).toUpperCase();let major=clean(formData.get('major'));const defense=clean(formData.get('defenseType')).toLowerCase(),contact=clean(formData.get('contactPerson')),email=clean(formData.get('contactEmail')),number=clean(formData.get('contactNumber')),file=clean(formData.get('researchFileUrl')),instructor=clean(formData.get('instructorId'))||null,adviser=clean(formData.get('adviserId'))||null,members=clean(formData.get('members')).split(/\r?\n/).map(x=>x.trim()).filter(Boolean)
 if(!id)redirect('/admin/groups');if(!title)fail(id,'Research title is required.');if(!contact)fail(id,'Contact person is required.');if(!PROGRAMS.has(program))fail(id,'Select a valid program.');if(!DEFENSES.has(defense))fail(id,'Select a valid defense type.');if(members.length<1||members.length>20)fail(id,'Enter between 1 and 20 group members, one name per line.');if(program==='BSED'&&!BSED.has(major))fail(id,'Select a valid BSED major.');if(program==='BSBA'&&!BSBA.has(major))fail(id,'Select a valid BSBA major.');if(['BEED','BSA','BSAIS'].includes(program))major='';if(file&&!/^https:\/\/(drive|docs)\.google\.com\//i.test(file))fail(id,'Enter a valid Google Drive research file link.')
 const supabase=await createClient(),{data:claims}=await supabase.auth.getClaims(),uid=claims?.claims?.sub;if(!uid)redirect('/admin');const{data:admin}=await supabase.from('admin_profiles').select('user_id').eq('user_id',uid).eq('is_active',true).maybeSingle();if(!admin)redirect('/admin')
 const[{data:current},{data:oldMembers}]=await Promise.all([supabase.from('research_groups').select('instructor_id,adviser_id,status').eq('id',id).maybeSingle(),supabase.from('group_members').select('id,sort_order').eq('research_group_id',id).order('sort_order',{ascending:true})]);if(!current)fail(id,'Research group not found.');if(current.status==='completed')redirect(`/admin/groups/${id}?error=${encodeURIComponent('Completed research records are protected and cannot be edited.')}`);if(current.status==='cancelled')redirect(`/admin/groups/${id}?error=${encodeURIComponent('Legacy Cancelled records are protected and cannot be edited.')}`)
 if(instructor&&instructor!==current.instructor_id){const{data}=await supabase.from('faculty').select('id').eq('id',instructor).eq('is_active',true).eq('can_teach_research',true).maybeSingle();if(!data)fail(id,'Selected research instructor is unavailable.')}
 if(adviser&&adviser!==current.adviser_id){const{data}=await supabase.from('faculty').select('id').eq('id',adviser).eq('is_active',true).eq('can_advise',true).maybeSingle();if(!data)fail(id,'Selected research adviser is unavailable.')}
 const{error:groupError}=await supabase.from('research_groups').update({title,program,major:major||null,defense_type:defense,contact_person:contact,contact_email:email||null,contact_number:number||null,research_file_url:file||null,instructor_id:instructor,adviser_id:adviser}).eq('id',id);if(groupError)fail(id,'Unable to save the research information. Please try again.')
 const old=oldMembers??[],rows=members.map((full_name,index)=>({id:old[index]?.id??crypto.randomUUID(),research_group_id:id,full_name,sort_order:index}));const{error:memberError}=await supabase.from('group_members').upsert(rows);if(memberError)fail(id,'Research information was saved, but the group members could not be updated. Please try again.');const obsolete=old.slice(members.length).map(x=>x.id);if(obsolete.length){const{error}=await supabase.from('group_members').delete().in('id',obsolete);if(error)fail(id,'The group was updated, but older member rows could not be removed. Please review the member list.')}
 for(const path of ['/','/schedule','/admin/dashboard','/admin/groups',`/admin/groups/${id}`,`/admin/groups/${id}/edit`,'/admin/schedule'])revalidatePath(path);redirect(`/admin/groups/${id}/edit?saved=1`)
}
