'use client'

import Link from 'next/link'
import { FormEvent, useMemo, useState } from 'react'
import RoleFacultySearch, { SubmissionFaculty } from './role-faculty-search'

type Mode = 'choice' | 'new' | 'continue'
type DefenseType = 'title' | 'proposal' | 'final'
type Values = { title: string; program: string; major: string; researchFileUrl: string; contactPerson: string; contactEmail: string; contactNumber: string; instructorId: string; adviserId: string }
type ExistingGroup = Values & { publicCode: string; members: string[] }
type VerifyResult = { verified?: boolean; canContinue?: boolean; reason?: string | null; currentDefenseType?: string | null; currentStatus?: string; nextDefenseType?: DefenseType | null; group?: ExistingGroup; error?: string }
type Success = { publicCode: string; accessKey?: string; defenseType: DefenseType; continued: boolean }

const BSED_MAJORS = ['English', 'Filipino', 'Mathematics', 'Science']
const BSBA_MAJORS = ['MM', 'FM', 'HRM']
function defenseLabel(value: string | null | undefined) { return value === 'title' ? 'Title Defense' : value === 'proposal' ? 'Proposal Defense' : value === 'final' ? 'Final Defense' : 'Research Defense' }
const EMPTY: Values = { title: '', program: '', major: '', researchFileUrl: '', contactPerson: '', contactEmail: '', contactNumber: '', instructorId: '', adviserId: '' }
function validDrive(value: string) { try { const url = new URL(value.trim()); return url.protocol === 'https:' && ['drive.google.com', 'docs.google.com'].includes(url.hostname) } catch { return false } }

function ResearchRequestForm({ faculty, mode, defenseType, initial, access, onBack }: { faculty: SubmissionFaculty[]; mode: 'new' | 'continue'; defenseType: DefenseType; initial?: ExistingGroup; access?: { publicCode: string; accessKey: string }; onBack: () => void }) {
  const availableIds = useMemo(() => new Set(faculty.map((person) => person.id)), [faculty])
  const [values, setValues] = useState<Values>(() => ({ ...(initial ?? EMPTY), instructorId: initial?.instructorId && availableIds.has(initial.instructorId) ? initial.instructorId : '', adviserId: initial?.adviserId && availableIds.has(initial.adviserId) ? initial.adviserId : '' }))
  const [members, setMembers] = useState<string[]>(initial?.members?.length ? initial.members : ['', '', ''])
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState<Success | null>(null)
  const [copied, setCopied] = useState(false)
  const instructorFaculty = useMemo(() => faculty.filter((person) => person.can_teach_research), [faculty])
  const adviserFaculty = useMemo(() => faculty.filter((person) => person.can_advise), [faculty])
  const majors = values.program === 'BSED' ? BSED_MAJORS : values.program === 'BSBA' ? BSBA_MAJORS : []
  const cleanMembers = members.map((name) => name.trim()).filter(Boolean)

  function setValue<K extends keyof Values>(key: K, value: Values[K]) { setValues((current) => { const next = { ...current, [key]: value }; if (key === 'program' && current.program !== value) next.major = ''; return next }); setError('') }
  function validate() {
    if (!values.title.trim()) return 'Enter the research title.'
    if (!values.program) return 'Select the program.'
    if (majors.length && !values.major) return 'Select the major.'
    if (!cleanMembers.length) return 'Enter at least one group member.'
    if (!values.contactPerson.trim()) return 'Enter the contact person.'
    if (values.contactEmail && !/^\S+@\S+\.\S+$/.test(values.contactEmail)) return 'Enter a valid email address or leave it blank.'
    if (!validDrive(values.researchFileUrl)) return 'Use a valid Google Drive or Google Docs research file link.'
    return ''
  }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const issue = validate(); if (issue) return setError(issue); setSubmitting(true); setError('')
    try {
      const response = await fetch('/api/submissions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ mode, publicCode: access?.publicCode, accessKey: access?.accessKey, title: values.title.trim(), program: values.program, major: values.major || null, researchFileUrl: values.researchFileUrl.trim(), contactPerson: values.contactPerson.trim(), contactEmail: values.contactEmail.trim(), contactNumber: values.contactNumber.trim(), instructorId: values.instructorId || null, adviserId: values.adviserId || null, members: cleanMembers }) })
      const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to submit the defense request.')
      setSuccess({ publicCode: result.publicCode, accessKey: result.accessKey, defenseType: result.defenseType, continued: Boolean(result.continued) })
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to submit the defense request.') } finally { setSubmitting(false) }
  }
  async function copyCredentials() {
    if (!success) return
    const text = success.accessKey ? `Research ID: ${success.publicCode}\nAccess Key: ${success.accessKey}` : `Research ID: ${success.publicCode}`
    try { await navigator.clipboard.writeText(text); setCopied(true) } catch { setCopied(false) }
  }
  if (success) return <div className="card lifecycle-success" aria-live="polite"><div className="submission-success-icon" aria-hidden="true">✓</div><p className="eyebrow">{success.continued ? 'Defense Request Received' : 'Research Created'}</p><h2>{success.continued ? `${defenseLabel(success.defenseType)} requested.` : 'Keep these research credentials.'}</h2><p>{success.continued ? 'Your Research ID stays the same. The administrator can now prepare the next defense schedule.' : 'Your Research ID stays with this research through Title, Proposal, and Final Defense. Save the Access Key because it is required for future defense requests.'}</p><div className="lifecycle-credentials"><div><span>Research ID</span><strong>{success.publicCode}</strong></div>{success.accessKey ? <div className="access-key-box"><span>Access Key · shown once</span><strong>{success.accessKey}</strong></div> : null}</div>{success.accessKey ? <div className="alert alert-warning">Save the Access Key now. For security, it will not be shown again after you leave this page.</div> : null}<div className="submission-success-actions"><button className="button" onClick={copyCredentials} type="button">{copied ? 'Copied ✓' : 'Copy Credentials'}</button><Link className="button button-secondary" href={`/status?code=${encodeURIComponent(success.publicCode)}`}>Check Status</Link><button className="button button-secondary" onClick={onBack} type="button">Done</button></div></div>

  return <form className="card lifecycle-form" onSubmit={submit}><div className="lifecycle-form-head"><div><p className="eyebrow">{mode === 'new' ? 'New Research' : 'Continue Existing Research'}</p><h2>{defenseLabel(defenseType)}</h2><p>{mode === 'new' ? 'A permanent Research ID will be created for this group.' : `Continuing ${access?.publicCode}. Review and update anything that changed.`}</p></div><button className="button button-secondary button-small" onClick={onBack} type="button">Back</button></div>{error ? <div className="alert alert-error" role="alert">{error}</div> : null}
    <section className="lifecycle-form-section"><h3>Research</h3><div className="field-grid"><div className="field full"><label htmlFor={`${mode}-title`}>Research title <span className="required-mark">*</span></label><textarea id={`${mode}-title`} maxLength={500} onChange={(event) => setValue('title', event.target.value)} value={values.title} /></div><div className="field"><label>Defense stage</label><input readOnly value={defenseLabel(defenseType)} /></div><div className="field"><label htmlFor={`${mode}-program`}>Program <span className="required-mark">*</span></label><select id={`${mode}-program`} onChange={(event) => setValue('program', event.target.value)} value={values.program}><option value="">Select program</option><option value="BEED">BEED</option><option value="BSED">BSED</option><option value="BSA">BSA</option><option value="BSAIS">BSAIS</option><option value="BSBA">BSBA</option></select></div>{majors.length ? <div className="field"><label htmlFor={`${mode}-major`}>Major <span className="required-mark">*</span></label><select id={`${mode}-major`} onChange={(event) => setValue('major', event.target.value)} value={values.major}><option value="">Select major</option>{majors.map((major) => <option key={major}>{major}</option>)}</select></div> : null}</div></section>
    <section className="lifecycle-form-section"><div className="lifecycle-section-head"><div><h3>Group members</h3><p>Review the current group and update names only when needed.</p></div></div><div className="submission-member-list">{members.map((member, index) => <div className="submission-member-row" key={`${index}-${members.length}`}><div className="field"><label htmlFor={`${mode}-member-${index}`}>Member {index + 1}{index === 0 ? <span className="required-mark"> *</span> : null}</label><input id={`${mode}-member-${index}`} maxLength={150} onChange={(event) => setMembers((current) => current.map((value, i) => i === index ? event.target.value : value))} value={member} /></div><button aria-label={`Remove member ${index + 1}`} className="button button-secondary submission-remove-member" disabled={members.length === 1} onClick={() => setMembers((current) => current.filter((_, i) => i !== index))} type="button">−</button></div>)}</div><button className="button button-secondary button-small" disabled={members.length >= 20} onClick={() => setMembers((current) => [...current, ''])} type="button">+ Add Member</button><div className="field-grid lifecycle-faculty-grid"><RoleFacultySearch faculty={instructorFaculty} id={`${mode}-instructor`} label="Research instructor" onChange={(value) => setValue('instructorId', value)} value={values.instructorId} /><RoleFacultySearch faculty={adviserFaculty} id={`${mode}-adviser`} label="Research adviser" onChange={(value) => setValue('adviserId', value)} value={values.adviserId} /></div></section>
    <section className="lifecycle-form-section"><h3>Contact & research file</h3><div className="field-grid"><div className="field"><label htmlFor={`${mode}-contact`}>Contact person <span className="required-mark">*</span></label><input id={`${mode}-contact`} maxLength={150} onChange={(event) => setValue('contactPerson', event.target.value)} value={values.contactPerson} /></div><div className="field"><label htmlFor={`${mode}-email`}>Email <span className="optional-mark">Optional</span></label><input id={`${mode}-email`} maxLength={254} onChange={(event) => setValue('contactEmail', event.target.value)} type="email" value={values.contactEmail} /></div><div className="field"><label htmlFor={`${mode}-number`}>Contact number <span className="optional-mark">Optional</span></label><input id={`${mode}-number`} maxLength={40} onChange={(event) => setValue('contactNumber', event.target.value)} value={values.contactNumber} /></div><div className="field full"><label htmlFor={`${mode}-file`}>Google Drive research file link <span className="required-mark">*</span></label><input id={`${mode}-file`} maxLength={2048} onChange={(event) => setValue('researchFileUrl', event.target.value)} placeholder="https://drive.google.com/..." type="url" value={values.researchFileUrl} /><p className="submission-field-help">Use a Drive or Docs link that the panel can open.</p></div></div></section>
    <div className="lifecycle-form-actions"><span><span className="required-mark">*</span> Required field</span><button className="button" disabled={submitting} type="submit">{submitting ? 'Submitting…' : mode === 'new' ? 'Create Research Record' : `Request ${defenseLabel(defenseType)}`}</button></div></form>
}

function ContinueAccess({ faculty, onBack }: { faculty: SubmissionFaculty[]; onBack: () => void }) {
  const [publicCode, setPublicCode] = useState(''), [accessKey, setAccessKey] = useState(''), [loading, setLoading] = useState(false), [error, setError] = useState(''), [result, setResult] = useState<VerifyResult | null>(null)
  async function verify(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); setResult(null); try { const response = await fetch('/api/research-access', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ publicCode, accessKey }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to verify the research record.'); setResult(data) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to verify the research record.') } finally { setLoading(false) } }
  if (result?.verified && result.canContinue && result.nextDefenseType && result.group) return <ResearchRequestForm access={{ publicCode: result.group.publicCode, accessKey }} defenseType={result.nextDefenseType} faculty={faculty} initial={result.group} mode="continue" onBack={onBack} />
  return <div className="lifecycle-access-shell"><form className="card lifecycle-access-card" onSubmit={verify}><div className="lifecycle-form-head"><div><p className="eyebrow">Continue Existing Research</p><h2>Verify your research.</h2><p>Use the same Research ID and private Access Key issued when the research was first submitted.</p></div><button className="button button-secondary button-small" onClick={onBack} type="button">Back</button></div>{error ? <div className="alert alert-error" role="alert">{error}</div> : null}{result?.reason ? <div className="alert alert-warning">{result.reason} <Link href={`/status?code=${encodeURIComponent(publicCode.trim())}`}>Check status →</Link></div> : null}<div className="field-grid"><div className="field"><label htmlFor="continue-code">Research ID <span className="required-mark">*</span></label><input autoCapitalize="characters" id="continue-code" onChange={(event) => setPublicCode(event.target.value.toUpperCase())} placeholder="RD-XXXXXXXX" value={publicCode} /></div><div className="field"><label htmlFor="continue-key">Access Key <span className="required-mark">*</span></label><input autoCapitalize="characters" id="continue-key" onChange={(event) => setAccessKey(event.target.value.toUpperCase())} placeholder="XXXXXX-XXXXXX-XXXXXX" value={accessKey} /></div></div><div className="lifecycle-form-actions"><Link className="text-link" href="/status">I only want to check status</Link><button className="button" disabled={loading} type="submit">{loading ? 'Verifying…' : 'Continue'}</button></div></form></div>
}

export default function SubmissionPortal({ faculty }: { faculty: SubmissionFaculty[] }) {
  const [mode, setMode] = useState<Mode>('choice')
  if (mode === 'new') return <ResearchRequestForm defenseType="title" faculty={faculty} mode="new" onBack={() => setMode('choice')} />
  if (mode === 'continue') return <ContinueAccess faculty={faculty} onBack={() => setMode('choice')} />
  return <div className="lifecycle-choice"><button className="card lifecycle-choice-card" onClick={() => setMode('new')} type="button"><span className="lifecycle-choice-number">01</span><strong>New Research</strong><p>First submission. Start with Title Defense and receive a permanent Research ID plus Access Key.</p><span>Start new research →</span></button><button className="card lifecycle-choice-card" onClick={() => setMode('continue')} type="button"><span className="lifecycle-choice-number">02</span><strong>Continue Existing Research</strong><p>Use your Research ID and Access Key to request Proposal or Final Defense after the previous stage is completed.</p><span>Continue research →</span></button><Link className="card lifecycle-choice-card lifecycle-status-choice" href="/status"><span className="lifecycle-choice-number">03</span><strong>Check Research Status</strong><p>Research ID only. See the current stage and published scheduling information.</p><span>Check status →</span></Link></div>
}
