import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import styles from './groups-v2.module.css'

type Params={q?:string;status?:string;program?:string;defense?:string;page?:string}
type Group={id:string;public_code:string;title:string;program:string|null;major:string|null;defense_type:string|null;status:string;group_members:{full_name:string}[]|null;defense_schedules:{defense_date:string;start_time:string;venue:string}[]|{defense_date:string;start_time:string;venue:string}|null}
const PAGE_SIZE=20
const STATUSES=new Set(['pending','scheduled','completed','cancelled'])
const PROGRAMS=new Set(['BEED','BSED','BSA','BSAIS','BSBA'])
const DEFENSES=new Set(['title','proposal','final'])
function one<T>(v:T|T[]|null|undefined){return !v?null:Array.isArray(v)?v[0]??null:v}
function defenseLabel(v:string|null){return v==='title'?'Title Defense':v==='proposal'?'Proposal Defense':v==='final'?'Final Defense':'Not recorded'}
function programLabel(g:Group){return g.program?`${g.program}${g.major?` - ${g.major}`:''}`:'Program not recorded'}
function dateLabel(v:string){const[y,m,d]=v.split('-').map(Number);return new Intl.DateTimeFormat('en-PH',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(y,m-1,d)))}
function timeLabel(v:string){const[h0,m='00']=v.split(':');let h=Number(h0);const ap=h>=12?'PM':'AM';h%=12;if(!h)h=12;return `${h}:${m} ${ap}`}
function href(p:Params,page:number){const q=new URLSearchParams();for(const k of ['q','status','program','defense'] as const)if(p[k])q.set(k,String(p[k]));if(page>1)q.set('page',String(page));const s=q.toString();return s?`/admin/groups?${s}`:'/admin/groups'}

export default async function ResearchGroupsV2({searchParams}:{searchParams:Promise<Params>}){
 const p=await searchParams;const search=String(p.q??'').trim().slice(0,150);const status=STATUSES.has(String(p.status))?String(p.status):null;const program=PROGRAMS.has(String(p.program).toUpperCase())?String(p.program).toUpperCase():null;const defense=DEFENSES.has(String(p.defense))?String(p.defense):null;const page=Math.max(1,parseInt(p.page??'1',10)||1)
 const supabase=await createClient();const{data:claims}=await supabase.auth.getClaims();const uid=claims?.claims?.sub;if(!uid)redirect('/admin');const{data:admin}=await supabase.from('admin_profiles').select('user_id').eq('user_id',uid).eq('is_active',true).maybeSingle();if(!admin)redirect('/admin')
 let ids:string[]|null=null
 if(search){const pattern=`%${search}%`;const[a,b,c,d]=await Promise.all([supabase.from('research_groups').select('id').ilike('title',pattern).limit(500),supabase.from('research_groups').select('id').ilike('public_code',pattern).limit(500),supabase.from('research_groups').select('id').ilike('contact_person',pattern).limit(500),supabase.from('group_members').select('research_group_id').ilike('full_name',pattern).limit(500)]);ids=[...new Set([...(a.data??[]).map(x=>x.id),...(b.data??[]).map(x=>x.id),...(c.data??[]).map(x=>x.id),...(d.data??[]).map(x=>x.research_group_id)])]}
 let q=supabase.from('research_groups').select('id,public_code,title,program,major,defense_type,status,group_members(full_name),defense_schedules(defense_date,start_time,venue)',{count:'exact'}).order('submitted_at',{ascending:false})
 if(ids)q=ids.length?q.in('id',ids):q.in('id',['00000000-0000-0000-0000-000000000000']);if(status)q=q.eq('status',status);if(program)q=q.eq('program',program);if(defense)q=q.eq('defense_type',defense)
 const from=(page-1)*PAGE_SIZE;const{data,count,error}=await q.range(from,from+PAGE_SIZE-1);const total=count??0;const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));if(page>pages&&total)redirect(href(p,pages));const groups=(data??[]) as Group[];const filters=[status,program,defense].filter(Boolean).length
 return <section className={`section ${styles.page}`}><div className="container">
  <div className={styles.heading}><div><p className="eyebrow">Research Groups</p><h2>Research submissions</h2><p>Open a submission to schedule its defense, or edit information when a correction is needed.</p></div><Link className="button button-secondary button-small" href="/admin/dashboard">← Dashboard</Link></div>
  <form className={`card ${styles.toolbar}`} method="get"><div className={styles.searchRow}><div className="field"><label htmlFor="q">Search</label><input defaultValue={search} id="q" name="q" placeholder="Research title, code, member, or contact person" type="search"/></div><button className="button" type="submit">Search</button></div><details className={styles.filters} open={filters>0}><summary>Filters{filters?` (${filters})`:''}</summary><div className={styles.filterGrid}><div className="field"><label htmlFor="status">Status</label><select defaultValue={status??''} id="status" name="status"><option value="">All statuses</option><option value="pending">Pending</option><option value="scheduled">Scheduled</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div><div className="field"><label htmlFor="program">Program</label><select defaultValue={program??''} id="program" name="program"><option value="">All programs</option>{['BEED','BSED','BSA','BSAIS','BSBA'].map(x=><option key={x} value={x}>{x}</option>)}</select></div><div className="field"><label htmlFor="defense">Defense type</label><select defaultValue={defense??''} id="defense" name="defense"><option value="">All defense types</option><option value="title">Title Defense</option><option value="proposal">Proposal Defense</option><option value="final">Final Defense</option></select></div><button className="button button-secondary" type="submit">Apply Filters</button></div></details>{(search||filters)?<Link className="button button-secondary button-small" href="/admin/groups">Clear search and filters</Link>:null}</form>
  <div className={styles.results}><span><strong>{total}</strong> {total===1?'research group':'research groups'}</span><span>Page {page} of {pages}</span></div>
  {error?<div className={`card ${styles.empty}`}><h3>Research groups could not be loaded.</h3><p>Please try again.</p></div>:!groups.length?<div className={`card ${styles.empty}`}><h3>No matching research groups.</h3><p>Adjust the search or filters to see other submissions.</p></div>:<div className={styles.list}>{groups.map(g=>{const s=one(g.defense_schedules);const members=g.group_members?.length??0;return <article className={`card ${styles.row}`} key={g.id}><div className={styles.main}><div className={styles.labels}><span className="code">{g.public_code}</span><span className={`status-pill status-${g.status}`}>{g.status}</span></div><h3>{g.title}</h3><div className={styles.meta}><span>{programLabel(g)}</span><span>{defenseLabel(g.defense_type)}</span><span>{members} {members===1?'member':'members'}</span></div><div className={styles.schedule}>{s?`Defense: ${dateLabel(s.defense_date)} · ${timeLabel(s.start_time)} · ${s.venue}`:'Not scheduled'}</div></div><div className={styles.actions}><Link className="button" href={`/admin/groups/${g.id}`}>Open</Link><Link className="button button-secondary" href={`/admin/groups/${g.id}/edit`}>Edit</Link></div></article>})}</div>}
  {pages>1?<nav className={styles.pagination} aria-label="Research groups pagination">{page>1?<Link className="button button-secondary button-small" href={href(p,page-1)}>← Previous</Link>:<span/>}<span>Page <strong>{page}</strong> of <strong>{pages}</strong></span>{page<pages?<Link className="button button-secondary button-small" href={href(p,page+1)}>Next →</Link>:<span/>}</nav>:null}
 </div></section>
}
