import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'

type DefenseType='title'|'proposal'|'final'
type FacultyName={full_name:string}
type PanelAssignment={panel_role:'chair'|'member';sort_order:number;faculty:FacultyName|FacultyName[]|null}
type ResearchGroup={public_code:string}
type ResearchDefense={defense_type:DefenseType|null;status:string;title_snapshot:string;program_snapshot:string|null;major_snapshot:string|null}
type ScheduleRow={id:string;defense_date:string;start_time:string;end_time:string;venue:string;research_groups:ResearchGroup|ResearchGroup[]|null;research_defenses:ResearchDefense|ResearchDefense[]|null;panel_assignments:PanelAssignment[]|null}
function one<T>(value:T|T[]|null|undefined):T|null{return!value?null:Array.isArray(value)?value[0]??null:value}
function manilaTodayKey(){const parts=new Intl.DateTimeFormat('en-US',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Asia/Manila'}).formatToParts(new Date()),values=Object.fromEntries(parts.map(part=>[part.type,part.value]));return`${values.year}-${values.month}-${values.day}`}
function formatDate(value:string){const[y,m,d]=value.split('-').map(Number);return new Intl.DateTimeFormat('en-PH',{weekday:'long',month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(y,m-1,d)))}
function formatTime(value:string){const[h,m]=value.split(':');let hour=Number(h);const suffix=hour>=12?'PM':'AM';hour%=12;if(!hour)hour=12;return`${hour}:${m??'00'} ${suffix}`}
function defenseLabel(value:DefenseType|null){return value==='title'?'Title Defense':value==='proposal'?'Proposal Defense':value==='final'?'Final Defense':'Research Defense'}
function programLabel(stage:ResearchDefense){return stage.program_snapshot?`${stage.program_snapshot}${stage.major_snapshot?` - ${stage.major_snapshot}`:''}`:'Program not recorded'}

export default async function MinimalHomeV2(){
 const today=manilaTodayKey(),supabase=await createClient(),{data,error}=await supabase.from('defense_schedules').select(`id, defense_date, start_time, end_time, venue, research_groups!inner (public_code), research_defenses!inner (defense_type, status, title_snapshot, program_snapshot, major_snapshot), panel_assignments (panel_role, sort_order, faculty (full_name))`).eq('is_published',true).eq('defense_date',today).eq('research_defenses.status','scheduled').order('start_time',{ascending:true}),schedules=(data??[]) as ScheduleRow[]
 return <><section className="minimal-home-hero"><div className="container minimal-home-inner"><h1>Submit your research. Check your defense schedule.</h1><div className="minimal-home-actions"><Link className="button" href="/submit">Submit Research</Link><Link className="button button-secondary" href="/status">Check Status</Link><Link className="button button-secondary" href="/schedule">Browse Schedule</Link></div></div></section><section className="section minimal-today-section"><div className="container"><div className="minimal-section-heading"><div><p className="eyebrow">Defense Today</p><h2>{formatDate(today)}</h2></div>{!error?<span>{schedules.length} {schedules.length===1?'defense':'defenses'}</span>:null}</div>{error?<div className="minimal-empty"><h3>Today&apos;s defenses are temporarily unavailable.</h3><p>Please try again later.</p></div>:schedules.length===0?<div className="minimal-empty"><h3>No defenses scheduled today.</h3><p>Use Browse Schedule to check upcoming published defenses, or Check Status with your Research ID.</p></div>:<div className="minimal-today-list">{schedules.map(schedule=>{const group=one(schedule.research_groups),stage=one(schedule.research_defenses);if(!group||!stage)return null;const panel=[...(schedule.panel_assignments??[])].sort((a,b)=>a.sort_order-b.sort_order),chair=panel.find(item=>item.panel_role==='chair'),chairName=one(chair?.faculty)?.full_name??null,members=panel.filter(item=>item.panel_role==='member').map(item=>one(item.faculty)?.full_name).filter((name):name is string=>Boolean(name));return <article className="minimal-defense-card" key={schedule.id}><div className="minimal-defense-time"><strong>{formatTime(schedule.start_time)}</strong><span>– {formatTime(schedule.end_time)}</span></div><div className="minimal-defense-content"><div className="minimal-defense-labels"><span className={`public-defense-badge type-${stage.defense_type??'general'}`}>{defenseLabel(stage.defense_type)}</span><span className="public-program-badge">{programLabel(stage)}</span></div><h3>{stage.title_snapshot}</h3><p className="minimal-venue">{schedule.venue}</p><small>{group.public_code}</small></div><div className="minimal-panel"><div><span>Panel Chair</span><strong>{chairName??'Not listed'}</strong></div><div><span>Panel Members</span><p>{members.length?members.join(', '):'Not listed'}</p></div></div></article>})}</div>}</div></section></>
}
