'use client'

import { useEffect, useRef, useState, useTransition } from 'react'
import { useFormStatus } from 'react-dom'
import { deletePendingResearchRecord } from './record/actions'
import recordStyles from './workspace-record-options.module.css'

type Props={groupId:string;publicCode:string;stageStatus?:string;status?:string;hasSchedule:boolean;locked:boolean;canDeleteRecord?:boolean}
export default function WorkspaceFormControlsV8({groupId,publicCode,stageStatus,status,hasSchedule,locked,canDeleteRecord=false}:Props){
 const{pending}=useFormStatus();const rootRef=useRef<HTMLDivElement>(null);const[dirty,setDirty]=useState(false);const[confirmCode,setConfirmCode]=useState('');const[recordPending,startRecordTransition]=useTransition()
 useEffect(()=>{const form=rootRef.current?.closest('form');if(!form)return;const mark=()=>setDirty(true),clear=()=>setDirty(false),panel=(event:Event)=>{if((event.target as Element|null)?.closest('.workspace-add-panel,.workspace-remove-panel'))setDirty(true)};form.addEventListener('input',mark);form.addEventListener('change',mark);form.addEventListener('click',panel);form.addEventListener('reset',clear);form.addEventListener('submit',clear);return()=>{form.removeEventListener('input',mark);form.removeEventListener('change',mark);form.removeEventListener('click',panel);form.removeEventListener('reset',clear);form.removeEventListener('submit',clear)}},[])
 useEffect(()=>{if(!dirty)return;const unload=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''},guard=(event:MouseEvent)=>{const anchor=(event.target as Element|null)?.closest('a[href]') as HTMLAnchorElement|null;if(anchor&&anchor.target!=='_blank'&&!window.confirm('You have unsaved schedule changes. Leave this page?'))event.preventDefault()};window.addEventListener('beforeunload',unload);document.addEventListener('click',guard);return()=>{window.removeEventListener('beforeunload',unload);document.removeEventListener('click',guard)}},[dirty])
 function remove(){const fd=new FormData();fd.set('groupId',groupId);startRecordTransition(()=>{void deletePendingResearchRecord(fd)})}
 const effectiveStatus=stageStatus??status??'',statusLabel=effectiveStatus?effectiveStatus[0].toUpperCase()+effectiveStatus.slice(1):'Unknown',deleteReason=hasSchedule?'Unavailable · Defense history exists':'Unavailable · A permanent research record with defense history must be retained'
 return <><div className="workspace-form-actions" ref={rootRef}><div className="workspace-save-note"><strong>{locked?'Schedule editing is disabled.':dirty?'Changes have not been saved.':'No unsaved changes.'}</strong></div><div className="workspace-action-buttons"><button className="button button-secondary workspace-cancel-button" disabled={!dirty||pending||locked} onClick={()=>{rootRef.current?.closest('form')?.reset();setDirty(false)}} type="button">Discard Changes</button><button className="button workspace-save-button" disabled={pending||locked} type="submit">{pending?'Saving…':hasSchedule?'Save Changes':'Schedule Defense'}</button></div></div><details className={recordStyles.shell}><summary className={recordStyles.summary}><span>Record Options</span><span className={recordStyles.summaryStatus}>{statusLabel}</span></summary><div className={recordStyles.body}><details className={recordStyles.danger}><summary>Danger zone</summary><div className={recordStyles.dangerBody}><strong>Delete permanently</strong>{canDeleteRecord?<><label htmlFor={`workspace-confirm-code-${groupId}`}>Type <b>{publicCode}</b> to confirm</label><input autoComplete="off" disabled={dirty||recordPending} id={`workspace-confirm-code-${groupId}`} onChange={e=>setConfirmCode(e.target.value)} value={confirmCode}/><button className={recordStyles.deleteButton} disabled={dirty||recordPending||confirmCode.trim()!==publicCode} onClick={remove} type="button">{recordPending?'Working…':'Delete Permanently'}</button></>:<p className={recordStyles.unavailable}>{deleteReason}</p>}</div></details></div></details></>
}
