import Link from 'next/link'
import { createAdminClient } from '@/lib/supabase/admin'
import { defenseLabel, normalizeResearchCode } from '@/lib/research-access'

type Stage = { id: string; defense_type: string | null; status: string; requested_at: string; completed_at: string | null }
type Schedule = { research_defense_id: string; defense_date: string; start_time: string; end_time: string; venue: string; is_published: boolean }
const STAGE_ORDER = ['title', 'proposal', 'final'] as const
function formatDate(value: string) { const [year,month,day]=value.split('-').map(Number); return new Intl.DateTimeFormat('en-PH',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(year,month-1,day))) }
function formatTime(value: string) { const [h,m]=value.split(':'); let hour=Number(h); const suffix=hour>=12?'PM':'AM'; hour%=12; if(!hour)hour=12; return `${hour}:${m??'00'} ${suffix}` }
function ended(schedule: Schedule) { return new Date(`${schedule.defense_date}T${String(schedule.end_time).slice(0,8)}+08:00`).getTime()<=Date.now() }
function statusLabel(stage: Stage|undefined,schedule: Schedule|undefined) { if(!stage)return'Not requested'; if(stage.status==='pending')return'Pending scheduling'; if(stage.status==='completed')return'Completed'; if(stage.status==='cancelled')return'Cancelled'; if(stage.status==='scheduled'&&schedule&&ended(schedule))return'Awaiting confirmation'; if(stage.status==='scheduled')return'Scheduled'; return stage.status }

export default async function ResearchStatusPage({searchParams}:{searchParams:Promise<{code?:string}>}){
 const params=await searchParams,code=normalizeResearchCode(params.code),admin=createAdminClient(); let group:{id:string;public_code:string;title:string;program:string|null;major:string|null}|null=null;let stages:Stage[]=[];let schedules:Schedule[]=[];let lookupError=false
 if(code){const{data,error}=await admin.from('research_groups').select('id, public_code, title, program, major').eq('public_code',code).maybeSingle();if(error)lookupError=true;group=data;if(group){const[stageResult,scheduleResult]=await Promise.all([admin.from('research_defenses').select('id, defense_type, status, requested_at, completed_at').eq('research_group_id',group.id).order('requested_at'),admin.from('defense_schedules').select('research_defense_id, defense_date, start_time, end_time, venue, is_published').eq('research_group_id',group.id)]);lookupError=Boolean(stageResult.error||scheduleResult.error);stages=(stageResult.data??[]) as Stage[];schedules=(scheduleResult.data??[]) as Schedule[]}}
 const scheduleByStage=new Map(schedules.map(schedule=>[schedule.research_defense_id,schedule]));const stageByType=new Map<string,Stage>();for(const stage of stages)if(stage.defense_type)stageByType.set(stage.defense_type,stage);const programLabel=group?`${group.program??'Program not recorded'}${group.major?` - ${group.major}`:''}`:''
 return <section className="section status-lookup"><div className="container"><div className="minimal-page-heading"><div><p className="eyebrow">Research Status</p><h1>Check your research.</h1><p>Use the permanent Research ID issued to your group. No Access Key is needed to view status.</p></div><Link className="button button-secondary button-small" href="/">← Home</Link></div><form action="/status" className="card status-search-card" method="get"><div className="field"><label htmlFor="research-status-code">Research ID</label><input autoCapitalize="characters" defaultValue={code} id="research-status-code" name="code" placeholder="RD-XXXXXXXX" required/></div><button className="button button-small" type="submit">Check Status</button></form>{lookupError?<div className="alert alert-error">Research status is temporarily unavailable. Please try again.</div>:null}{code&&!lookupError&&!group?<div className="minimal-empty"><h3>Research ID not found.</h3><p>Check the code and try again.</p></div>:null}
 {group&&!lookupError?<><div className="card research-status-summary"><div className="schedule-labels"><span className="code">{group.public_code}</span></div><h1>{group.title}</h1><p>{programLabel}</p></div><div className="research-stage-list">{STAGE_ORDER.map(type=>{const stage=stageByType.get(type),schedule=stage?scheduleByStage.get(stage.id):undefined,label=statusLabel(stage,schedule),showPublishedDetails=stage?.status==='scheduled'&&schedule?.is_published&&!ended(schedule);return <article className="card research-stage-card" key={type}><div className="research-stage-name"><strong>{defenseLabel(type)}</strong><span className={`status-pill${stage?.status==='completed'?' status-completed':stage?.status==='scheduled'?' status-published':''}`}>{label}</span></div><div className="research-stage-detail">{!stage?<span>This stage has not been requested yet.</span>:null}{stage?.status==='pending'?<span>Your request has been received and is waiting for the administrator to schedule it.</span>:null}{stage?.status==='scheduled'&&schedule&&ended(schedule)?<span>The scheduled defense time has ended and is awaiting administrator confirmation.</span>:null}{stage?.status==='scheduled'&&!showPublishedDetails&&schedule&&!ended(schedule)?<span>The defense is scheduled. Details have not been published yet.</span>:null}{showPublishedDetails&&schedule?<><strong>{formatDate(schedule.defense_date)} · {formatTime(schedule.start_time)}–{formatTime(schedule.end_time)}</strong><span>Venue: {schedule.venue}</span></>:null}{stage?.status==='completed'?<span>{schedule?`Completed defense: ${formatDate(schedule.defense_date)}`:'This defense stage is completed.'}</span>:null}{stage?.status==='cancelled'?<span>Please contact the research administrator about this defense record.</span>:null}</div></article>})}{stages.some(stage=>!stage.defense_type)?<article className="card research-stage-card"><div className="research-stage-name"><strong>Legacy Defense Record</strong><span className="status-pill">Type not recorded</span></div><div className="research-stage-detail"><span>An older defense exists without a recorded stage. Contact the administrator if this must be corrected before continuing.</span></div></article>:null}</div></>:null}</div></section>
}
